<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.41.1" />
    <ProjectReference Include="..\..\UISupportBlazor\UISupportBlazor.csproj" Condition="Exists('..\..\UISupportBlazor\UISupportBlazor.csproj')" />
    <PackageReference Include="UISupportBlazor" Version="1.*" Condition="!Exists('..\..\UISupportBlazor\UISupportBlazor.csproj')" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BackEnd\InvoicesInCloudBackEnd.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
