<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <UserSecretsId>619b5325-302a-4b31-a137-2817a733a16e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UISupportBlazor\UISupportBlazor.csproj" Condition="Exists('..\..\UISupportBlazor\UISupportBlazor.csproj')" />
    <PackageReference Include="UISupportBlazor" Version="1.*" Condition="!Exists('..\..\UISupportBlazor\UISupportBlazor.csproj')" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
